### ISSUE TITLE
ModuleNotFound after fresh install

### ISSUE THREAD

**Issue by hajekad** [Mortafix/pysaber#4]
I've done pip3 install saberio, then saberio --config and got:`Traceback (most recent call last):
  File "/home/hajekad/.local/bin/saberio", line 5, in <module>
    from pysaber.saberio import main
  File "/home/hajekad/.local/lib/python3.9/site-packages/pysaber/saberio.py", line 6, in <module>
    from pysaber.utils.helpers import (SPINNER, download_song, get_info_by_code,
  File "/home/hajekad/.local/lib/python3.9/site-packages/pysaber/utils/helpers.py", line 7, in <module>
    from requests import get
ModuleNotFoundError: No module named 'requests'`

**Comment by hajekad** [comment]
Here is my another try on a windows machine:
Traceback (most recent call last):
  File "C:\Users\22ada\AppData\Local\Programs\Python\Python310\Scripts\saberio-script.py", line 33, in <module>
    sys.exit(load_entry_point('saberio==1.0.1', 'console_scripts', 'saberio')())
  File "C:\Users\22ada\AppData\Local\Programs\Python\Python310\Scripts\saberio-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\22ada\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Users\22ada\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\22ada\AppData\Local\Programs\Python\Python310\lib\site-packages\pysaber\saberio.py", line 6, in <module>
    from pysaber.utils.helpers import (SPINNER, download_song, get_info_by_code,
  File "C:\Users\22ada\AppData\Local\Programs\Python\Python310\lib\site-packages\pysaber\utils\helpers.py", line 7, in <module>
    from requests import get
ModuleNotFoundError: No module named 'requests'

**Comment by Mortafix** [comment]
Thanks, module `requests` added in requirements
